# Generated by Django 5.2 on 2025-05-01 20:28

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gateway', models.CharField(help_text='Name of the payment gateway used', max_length=50)),
                ('method', models.CharField(choices=[('wallet', 'Wallet'), ('upi', 'UPI'), ('card', 'Credit/Debit Card')], help_text='Payment method', max_length=20)),
                ('transaction_id', models.CharField(blank=True, help_text='Gateway-issued transaction ID (must be set when status=success)', max_length=255, null=True, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount charged', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('currency', models.CharField(default='INR', help_text='ISO 4217 currency code', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', help_text='Current payment status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_response', models.JSONField(default=dict, help_text='Full JSON payload from gateway')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='payments_pa_status_7ad4af_idx'), models.Index(fields=['created_at'], name='payments_pa_created_b8a300_idx')],
            },
        ),
    ]
