branch-defaults:
  main:
    environment: django-env-4
    group_suffix: null
environment-defaults:
  django-env-2:
    branch: null
    repository: null
  django-env-4:
    branch: null
    repository: null
global:
  application_name: django-tutorial
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.11
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
