# Generated by Django 5.2 on 2025-05-01 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Confirmation'), ('confirmed', 'Confirmed'), ('partial', 'Partially Paid'), ('paid', 'Fully Paid'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('returned', 'Returned')], default='pending', help_text='Current state in fulfillment workflow', max_length=15, verbose_name='Order Status'),
        ),
    ]
