# Generated by Django 5.2 on 2025-04-29 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_order_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='product',
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='products',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Tracks the number of units available in inventory', verbose_name='Stock Quantity'),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='The date and time when this record was first created', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='The date and time when this record was last updated', verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Category this product belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category'),
        ),
        migrations.AlterField(
            model_name='products',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='The date and time when this record was first created', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description of the product'),
        ),
        migrations.AlterField(
            model_name='products',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Toggle to make the product available or unavailable for orders'),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(help_text='The name of the product', max_length=100),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Current selling price (₹)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='products',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='The date and time when this record was last updated', verbose_name='Updated At'),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderProduct',
        ),
    ]
